name: rpl-hw2
channels:
  - pytorch
  - pytorch3d
  - nvidia
  - conda-forge
dependencies:
  - python=3.8
  - pip=23.3.2
  - cudatoolkit=11.6
  - pytorch=1.13.1
  - torchvision=0.14.1
  - pytorch-cuda=11.6
  # trick to avoid cpu affinity issue described in https://github.com/pytorch/pytorch/issues/99625
  - llvm-openmp=14
  # trick to force reinstall imagecodecs via pip
  - imagecodecs==2022.8.8